project:
  type: website
  output-dir: docs

website:
  title: "Data Seance"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daniel-j-miller
      - icon: mastodon
        href: https://aus.social/@Dan
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-miller-cbr/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

